comment: false
coverage:
  status:
    patch: false
    project:
      default:
        threshold: 1%
ignore:
  - .github
  - Commands
  - docs
  - icons
  - Keymaps
  - Menus
  - messages
  - stubs
  - Syntaxes
  - tests
