# AUTOGENERATED - run X script to update.
# jq '[.contributions.settings[] | select(.schema."$id" | IN("sublime://settings/LSP", "sublime://LSP-settings")) | .schema] | add | walk(if type == "object" and has("$ref") then .["$ref"] |= gsub("^[^#]+"; "") else . end) | walk(if type == "object" then to_entries | sort_by(.key) | from_entries else . end)' sublime-package.json > test.json
# uv run datamodel-codegen --input test.json --input-file-type jsonschema --output-model-type typing.TypedDict --output model.py --custom-file-header "# AUTOGENERATED - run X script to update." --target-python-version 3.11 --class-name SettingsModel --formatters ruff-format ruff-check --collapse-root-models


from __future__ import annotations

from typing import Any
from typing import Literal
from typing import NotRequired
from typing import TypeAlias
from typing import TypedDict
from typing_extensions import TypedDict


class DiagnosticsHighlightStyle(TypedDict, closed=True):
    error: NotRequired[Literal['box', 'underline', 'stippled', 'squiggly', '']]
    hint: NotRequired[Literal['box', 'underline', 'stippled', 'squiggly', '']]
    info: NotRequired[Literal['box', 'underline', 'stippled', 'squiggly', '']]
    warning: NotRequired[Literal['box', 'underline', 'stippled', 'squiggly', '']]


class CompletionProvider(TypedDict):
    triggerCharacters: NotRequired[bool]


class DocumentOnTypeFormattingProvider(TypedDict):
    firstTriggerCharacter: NotRequired[bool]
    moreTriggerCharacter: NotRequired[bool]


class SignatureHelpProvider(TypedDict):
    retriggerCharacters: NotRequired[bool]
    triggerCharacters: NotRequired[bool]


class ClientExperimentalCapabilities(TypedDict):
    pass


class ClientInitializationOptions(TypedDict):
    pass


class ClientSettings(TypedDict):
    pass


class FileWatcher(TypedDict, closed=True):
    events: NotRequired[list[Literal['create', 'change', 'delete']]]
    ignores: NotRequired[list[str]]
    patterns: list[str]


class SemanticTokens1(TypedDict):
    pass


SemanticTokens: TypeAlias = list[str] | SemanticTokens1


class SettingsModel(TypedDict, closed=True):
    auto_show_diagnostics_panel: NotRequired[Literal['never', 'always', 'saved'] | bool]
    clients: NotRequired[Any]
    code_action_on_save_timeout_ms: NotRequired[int]
    completion_insert_mode: NotRequired[Literal['insert', 'replace']]
    default_clients: NotRequired[Any]
    diagnostics_additional_delay_auto_complete_ms: NotRequired[int]
    diagnostics_delay_ms: NotRequired[int]
    diagnostics_gutter_marker: NotRequired[Literal['dot', 'circle', 'bookmark', 'sign', '']]
    diagnostics_highlight_style: NotRequired[
        Literal['box', 'underline', 'stippled', 'squiggly', ''] | DiagnosticsHighlightStyle
    ]
    diagnostics_panel_include_severity_level: NotRequired[int]
    disabled_capabilities: NotRequired[list[Any]]
    document_highlight_style: NotRequired[Literal['background', 'underline', 'stippled', 'outline', '']]
    hover_highlight_style: NotRequired[Literal['background', 'underline', 'stippled', 'outline', '']]
    inhibit_snippet_completions: NotRequired[bool]
    inhibit_word_completions: NotRequired[bool]
    initially_folded: NotRequired[list[Literal['comment', 'imports', 'region'] | str]]
    inlay_hints_max_length: NotRequired[int]
    link_highlight_style: NotRequired[Literal['underline', 'none', 'disabled']]
    log_debug: NotRequired[bool]
    log_max_size: NotRequired[int]
    log_server: NotRequired[list[Literal['panel', 'remote']] | bool]
    lsp_code_actions_on_format: NotRequired[dict[str, bool]]
    lsp_code_actions_on_save: NotRequired[dict[str, bool]]
    lsp_format_on_paste: NotRequired[bool]
    lsp_format_on_save: NotRequired[bool]
    on_save_task_timeout_ms: NotRequired[int]
    only_show_lsp_completions: NotRequired[bool]
    popup_max_characters_height: NotRequired[int]
    popup_max_characters_width: NotRequired[int]
    refactoring_auto_save: NotRequired[Literal['always', 'preserve', 'preserve_opened', 'never']]
    semantic_highlighting: NotRequired[bool]
    show_code_actions: NotRequired[Literal['annotation', 'bulb', '']]
    show_code_actions_in_hover: NotRequired[bool]
    show_code_lens: NotRequired[Literal['annotation', 'phantom']]
    show_diagnostics_annotations_severity_level: NotRequired[Literal[0, 1, 2, 3, 4]]
    show_diagnostics_count_in_view_status: NotRequired[bool]
    show_diagnostics_highlights: NotRequired[bool]
    show_diagnostics_in_hover: NotRequired[bool]
    show_diagnostics_in_view_status: NotRequired[bool]
    show_diagnostics_panel_on_save: NotRequired[int]
    show_diagnostics_severity_level: NotRequired[int]
    show_inlay_hints: NotRequired[bool]
    show_multiline_diagnostics_highlights: NotRequired[bool]
    show_multiline_document_highlights: NotRequired[bool]
    show_references_in_quick_panel: NotRequired[bool]
    show_symbol_action_links: NotRequired[bool]
    show_view_status: NotRequired[bool]


class ClientDisabledCapabilities(TypedDict):
    callHierarchyProvider: NotRequired[dict[str, Any] | bool]
    codeActionProvider: NotRequired[dict[str, Any] | bool]
    codeLensProvider: NotRequired[dict[str, Any] | bool]
    colorProvider: NotRequired[dict[str, Any] | bool]
    completionProvider: NotRequired[CompletionProvider | bool]
    declarationProvider: NotRequired[dict[str, Any] | bool]
    definitionProvider: NotRequired[dict[str, Any] | bool]
    diagnosticProvider: NotRequired[dict[str, Any] | bool]
    documentFormattingProvider: NotRequired[dict[str, Any] | bool]
    documentHighlightProvider: NotRequired[dict[str, Any] | bool]
    documentLinkProvider: NotRequired[dict[str, Any] | bool]
    documentOnTypeFormattingProvider: NotRequired[DocumentOnTypeFormattingProvider | bool]
    documentRangeFormattingProvider: NotRequired[dict[str, Any] | bool]
    documentSymbolProvider: NotRequired[dict[str, Any] | bool]
    executeCommandProvider: NotRequired[dict[str, Any] | bool]
    foldingRangeProvider: NotRequired[dict[str, Any] | bool]
    hoverProvider: NotRequired[dict[str, Any] | bool]
    implementationProvider: NotRequired[dict[str, Any] | bool]
    inlayHintProvider: NotRequired[dict[str, Any] | bool]
    inlineValueProvider: NotRequired[dict[str, Any] | bool]
    linkedEditingRangeProvider: NotRequired[dict[str, Any] | bool]
    monikerProvider: NotRequired[dict[str, Any] | bool]
    referencesProvider: NotRequired[dict[str, Any] | bool]
    renameProvider: NotRequired[dict[str, Any] | bool]
    selectionRangeProvider: NotRequired[dict[str, Any] | bool]
    semanticTokensProvider: NotRequired[dict[str, Any] | bool]
    signatureHelpProvider: NotRequired[SignatureHelpProvider | bool]
    typeDefinitionProvider: NotRequired[dict[str, Any] | bool]
    typeHierarchyProvider: NotRequired[dict[str, Any] | bool]
    workspaceSymbolProvider: NotRequired[dict[str, Any] | bool]


class ClientConfig(TypedDict, closed=True):
    auto_complete_selector: NotRequired[str]
    command: NotRequired[list[str]]
    diagnostics_mode: NotRequired[Literal['open_files', 'workspace']]
    disabled_capabilities: NotRequired[ClientDisabledCapabilities]
    enabled: NotRequired[bool]
    env: NotRequired[dict[str, str | list[str]]]
    experimental_capabilities: NotRequired[ClientExperimentalCapabilities]
    file_watcher: NotRequired[FileWatcher]
    ignore_server_trigger_chars: NotRequired[bool]
    initializationOptions: NotRequired[ClientInitializationOptions]
    priority_selector: NotRequired[Any]
    schemes: NotRequired[list[str]]
    selector: NotRequired[str]
    settings: NotRequired[ClientSettings]
    tcp_port: NotRequired[int]
