import asyncio
import concurrent
import concurrent.futures
import sublime
import sublime_plugin
from _typeshed import Incomplete
from abc import ABCMeta
from collections.abc import Coroutine
from contextvars import Context
from typing import Any, Callable, TypeVar
from typing_extensions import ParamSpec

__all__ = ['__version__', 'active_window', 'ApplicationCommand', 'call_coroutine', 'call_soon_threadsafe', 'debounced', 'EventListener', 'InputCancelledError', 'run_coroutine', 'TextChangeListener', 'View', 'ViewCommand', 'ViewEventListener', 'Window', 'WindowCommand', 'windows']

P = ParamSpec('P')
T = TypeVar('T')
EL = TypeVar('EL', bound='EventListener')
VEL = TypeVar('VEL', bound='ViewEventListener')
__version__: str

class ExitEvent:
    @classmethod
    def aquire(cls) -> None: ...
    @classmethod
    def release(cls) -> None: ...
    @classmethod
    def wait(cls) -> None: ...

def debounced(delay_in_ms: int): ...
def run_coroutine(coro: Coroutine[object, object, T]) -> concurrent.futures.Future[T]: ...
def call_coroutine(coro: Coroutine[object, object, None]) -> asyncio.Handle: ...
def call_soon_threadsafe(callback: Callable[..., None], *args: Any, context: Context | None = None) -> asyncio.Handle: ...
def active_window() -> Window: ...
def windows() -> list[Window]: ...

class ApplicationCommand(sublime_plugin.ApplicationCommand):
    def run_(self, edit_token: int, args: Any) -> None: ...
    async def run(self, **kwargs: Any) -> None: ...

class WindowCommand(sublime_plugin.WindowCommand):
    window: Incomplete
    def __init__(self, window: sublime.Window) -> None: ...
    def run_(self, edit_token: int, args: Any) -> None: ...
    async def run(self, **kwargs: Any) -> None: ...

class ViewCommand(sublime_plugin.TextCommand):
    def run_(self, edit_token: int, args: Any) -> None: ...
    async def run(self, **kwargs: Any) -> None: ...

class CoroutineAdapter:
    coro_func: Incomplete
    def __init__(self, coro_func: Callable[..., Coroutine[object, object, None]]) -> None: ...
    def __call__(self, *args, **kwargs: Any) -> None: ...
    def callback(self, *args, **kwargs: Any) -> None: ...

class AsyncEventListenerType(ABCMeta):
    def __new__(mcs: type[AsyncEventListenerType], name: str, bases: tuple[type, ...], attrs: dict[str, object]) -> AsyncEventListenerType: ...

class EventListener(sublime_plugin.EventListener, metaclass=AsyncEventListenerType): ...
class ViewEventListener(sublime_plugin.ViewEventListener, metaclass=AsyncEventListenerType): ...

class AsyncTextChangeListenerType(ABCMeta):
    def __new__(mcs: type[AsyncTextChangeListenerType], name: str, bases: tuple[type, ...], attrs: dict[str, object]) -> AsyncTextChangeListenerType: ...

class TextChangeListener(sublime_plugin.TextChangeListener, metaclass=AsyncTextChangeListenerType): ...
class InputCancelledError(Exception): ...

class Window(sublime.Window):
    def active_view(self) -> View | None: ...
    def new_file(self, flags=..., syntax: str = '') -> View: ...
    def open_file(self, fname: str, flags=..., group: int = -1) -> View: ...
    def find_open_file(self, fname: str, group: int = -1) -> View | None: ...
    def views(self, *, include_transient: bool = False) -> list[View]: ...
    def active_view_in_group(self, group: int) -> View | None: ...
    def views_in_group(self, group: int) -> list[View]: ...
    def transient_view_in_group(self, group: int) -> View | None: ...
    def create_output_panel(self, name: str, unlisted: bool = False) -> View: ...
    def find_output_panel(self, name: str) -> View | None: ...
    async def show_input_panel(self, caption: str, initial_text: str = '', on_change: Callable[[sublime.View, str], Coroutine[object, object, T]] | None = None) -> str: ...
    async def show_quick_panel(self, items: list[str] | list[list[str]] | list[sublime.QuickPanelItem], flags: sublime.QuickPanelFlags = ..., selected_index: int = -1, on_highlight: Callable[[int], Coroutine[object, object, T]] | None = None, placeholder: str | None = None) -> int: ...

class View(sublime.View):
    def window(self) -> Window | None: ...
    def clones(self) -> list[View]: ...
